### ISSUE TITLE
Remove Invoice images in documentation relating to the API Builder training interface

### ISSUE THREAD

**Issue by EmmanuelleThomas** [mindee/documentation#13]
In the whole API Builder section of the the documentation, the examples and images should refer to custom documents and not Invoices. This applies to this page: https://developers.mindee.com/docs/training-interface 

Example here:
<img width="719" alt="Screenshot 2021-12-14 at 12 11 51" src="https://user-images.githubusercontent.com/96113811/146000602-efde6d0b-3913-4b69-956c-b0a3f81f5177.png">

**Comment by fakela** [comment]
@EmmanuelleThomas Thanks for this, this will updated accordingly
