### ISSUE TITLE
Update first image in Invoice OCR documentation

### ISSUE THREAD

**Issue by EmmanuelleThomas** [mindee/documentation#18]
Replace current image to display an invoice image instead
<img width="765" alt="image_documentation" src="https://user-images.githubusercontent.com/96113811/147591261-e198270e-0269-4512-bad0-8563104b6e1f.png">

**Comment by fakela** [comment]
<img width="459" alt="Screenshot 2022-01-03 at 14 40 38" src="https://user-images.githubusercontent.com/39309699/147937085-2d9a596f-2177-41ba-a0e8-eb258aaa2536.png">

@fharper here is the image added
