### ISSUE TITLE
Setup your account - SSO steps

### ISSUE THREAD

**Issue by fharper** [mindee/documentation#223]
Show step by step process to sign up with SSO on Google, and the same with GitHub

**Comment by fakela** [comment]
> Show step by step process to sign up with SSO on Google, and the same with GitHub

https://github.com/mindee/documentation/blob/main/get-started/setup-your-account.md this was done already (although there was some screenshots I needed to add which we created an issue for)

**Comment by fharper** [comment]
Oh, I forgot the sync issues 🤦‍♂️
