### ISSUE TITLE
Error in paragraph number

### ISSUE THREAD

**Issue by EmmanuelleThomas** [mindee/documentation#233]
There is a mistake on this page: title numbers start at 3, and the next one is at 4 (instead of 1 and 2)
<img width="790" alt="Screenshot 2022-01-13 at 17 31 21" src="https://user-images.githubusercontent.com/96113811/150868385-b9103031-f347-4fe6-b0ab-6ca82c4bae71.png">
.

**Comment by fharper** [comment]
Weird, README doesn't display all the page, so it's not an error, it's just missing some information that are in the documentation, but now shown to the user 🤦‍♂️

Checking what is happening.

**Comment by fharper** [comment]
Fixed
