### ISSUE TITLE
Platform Tour Modifications

### ISSUE THREAD

**Issue by fharper** [mindee/documentation#250]
- [x] 16: link to OTF API doc page on the OTF APIs words
- [x] 16: I think the second sentence is a bit long
- [x] 39: I would move this in the paragraph before listing them as it's super important, and we should let the user know before they check the APIs by location as they may not read past that.
- [x] 45: no need to repeat the word section
- [x] 46: same as 45
- [x] 48: we should add a screenshot there
- [x] 49: **the default** instead of **your default** as we may change it for customer right away after they create their account
- [x] 51: same as 48
- [x] 60: link to OTS
- [x] 60: we really need to find a better way to talk about the other documentation... Actually, I will suggest we change the name on the platform until we can merge it so it's less confusing
- [x] 90: **OpenAPI** not **Open API**
- [x] 90: OpenAPI **definition**, not **configuration**
- [x] 90: I would add an OpenAPI definition in the glossary and link there
- [x] 95: since the first sentences have keys in plural, do we need the next sentence?
- [x] 95: we need to think about the creation of an API part as it is weird to me that we link to another page and we explain how to delete it in this page. WDYT?
- [x] 97: should be ordered since it's a step by step list
- [x] 99: missing alt text

**Comment by fakela** [comment]
@fharper for checklist 95 b we can create a separate page for API keys that explains how to create and delete an API key

**Comment by fharper** [comment]
Sounds good as I don't think people need to know how to do that in a platform tour
