### ISSUE TITLE
Passport OCR Suggestions

### ISSUE THREAD

**Issue by fharper** [mindee/documentation#268]
- [x] 24: OTS & Use cases pages has been written as a detached tutorial, but I think we may want to consider they are part of the documentation, since they are. In that case, I would remove those points. WDYT?
- [x] 25: download = use
- [x] 33: I think we talk about that in the getting started section, not sure it add values here
- [x] 44: you missed a block code
- [x] 73: there is no {}
- [x] 73: or use the "select an API key and it will be filled automatically
- [x] 717: polygons don't show the level or accuracy, but the box enclosing the properties extracted

In all extracted properties we list with code examples, we are missing the ... before and after the code since they are part of a larger JSON response.

**Comment by fakela** [comment]
No 44 is a code with multiple tabs

**Comment by fakela** [comment]
> * [x]  24: OTS & Use cases pages has been written as a detached tutorial, but I think we may want to consider they are part of the documentation, since they are. In that case, I would remove those points. WDYT?
> * [x]  25: download = use
> * [x]  33: I think we talk about that in the getting started section, not sure it add values here
> * [x]  44: you missed a block code
> * [x]  73: there is no {}
> * [x]  73: or use the "select an API key and it will be filled automatically
> * [ ]  717: polygons don't show the level or accuracy, but the box enclosing the properties extracted
> 
> In all extracted properties we list with code examples, we are missing the ... before and after the code since they are part of a larger JSON response.

Yeah
