### ISSUE TITLE
Invoice OCR Suggestions

### ISSUE THREAD

**Issue by fharper** [mindee/documentation#269]
- [x] 15: what is etc here?
- [x] 18: same as passport, do we need those here or should we assume they went through the getting started section? I would say the latter
- [x] 37: shouldn't "Documentation > API reference" be in bold or code?
- [x] 37: there is nothing about replacing the API key here
- [x] 39: missed a code block
- [x] 528:  polygons don't show the level or accuracy, but the box enclosing the properties extracted

In all extracted properties we list with code examples, we are missing the ... before and after the code since they are part of a larger JSON response.

**Comment by fakela** [comment]
The Code block has multiple tabs
