### ISSUE TITLE
Create a perfect fake invoice for the Python invoice SDK

### ISSUE THREAD

**Issue by fakela** [mindee/documentation#366]

**Comment by fharper** [comment]
duplicate of https://github.com/mindee/devrel/issues/436

**Comment by fharper** [comment]
oh, the issue I wanted you to create is the one about updating the invoice page code examples and response once this invoice is created :)

**Comment by fakela** [comment]
Oh okay 😄

**Comment by fakela** [comment]
> oh, the issue I wanted you to create is the one about updating the invoice page code examples and response once this invoice is created :)

https://github.com/mindee/documentation/issues/328 it was already created 👍
